sudo: required
services:
  - docker

before_install:
  - docker build -t coffeedeficient/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true coffeedeficient/react-test npm test

after_success:
  - docker build -t coffeedeficient/multi-docker-client ./client
  - docker build -t coffeedeficient/multi-docker-nginx ./nginx
  - docker build -t coffeedeficient/multi-docker-server ./server
  - docker build -t coffeedeficient/multi-docker-worker ./worker

  #Docker CLI Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Push to Docker Hub
  - docker push coffeedeficient/multi-docker-client
  - docker push coffeedeficient/multi-docker-nginx
  - docker push coffeedeficient/multi-docker-server
  - docker push coffeedeficient/multi-docker-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-623433391941'
  bucket_path: 'docker-multi'
  on:
    branch: master    
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY